msgid ""
msgstr ""
"Project-Id-Version: scikit-learn\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2021-03-31 11:24-0400\n"
"PO-Revision-Date: 2021-06-13 01:01\n"
"Last-Translator: \n"
"Language-Team: Spanish\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.9.0\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Crowdin-Project: scikit-learn\n"
"X-Crowdin-Project-ID: 450526\n"
"X-Crowdin-Language: es-ES\n"
"X-Crowdin-File: /main/doc/en/modules/generated/sklearn.exceptions.FitFailedWarning.po\n"
"X-Crowdin-File-ID: 5838\n"
"Language: es_ES\n"

#: ../modules/generated/sklearn.exceptions.FitFailedWarning.rst:2
msgid ":mod:`sklearn.exceptions`.FitFailedWarning"
msgstr ":mod:`sklearn.exceptions`.FitFailedWarning"

#: of sklearn.exceptions.FitFailedWarning:2
msgid "Warning class used if there is an error while fitting the estimator."
msgstr "Clase de advertencia usada si hay un error mientras se ajusta el estimador."

#: of sklearn.exceptions.FitFailedWarning:4
msgid "This Warning is used in meta estimators GridSearchCV and RandomizedSearchCV and the cross-validation helper function cross_val_score to warn when there is an error while fitting the estimator."
msgstr "Esta advertencia se utiliza en los metaestimadores GridSearchCV y RandomizedSearchCV y en la función de ayuda de validación cruzada cross_val_score para advertir cuando hay un error al ajustar el estimador."

#: of sklearn.exceptions.FitFailedWarning:8
msgid "Moved from sklearn.cross_validation."
msgstr "Se ha movido de sklearn.cross_validation."

#: of sklearn.exceptions.FitFailedWarning
msgid "Attributes"
msgstr "Atributos"

#: of sklearn.exceptions.FitFailedWarning:25
msgid "**args**"
msgstr "**args**"

#: of sklearn.exceptions.FitFailedWarning:28
msgid "Methods"
msgstr "Métodos"

#: of sklearn.exceptions.FitFailedWarning:32:<autosummary>:1
msgid ":obj:`with_traceback <sklearn.exceptions.FitFailedWarning.with_traceback>`\\"
msgstr ":obj:`with_traceback <sklearn.exceptions.FitFailedWarning.with_traceback>`\\"

#: of sklearn.exceptions.FitFailedWarning.with_traceback:2
#: sklearn.exceptions.FitFailedWarning:32:<autosummary>:1
msgid "Exception.with_traceback(tb) -- set self.__traceback__ to tb and return self."
msgstr "Exception.with_traceback(tb) -- se establece self.__traceback__ en tb y devuelve self."

